/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MevBriberInterface extends ethers.utils.Interface {
  functions: {
    "check32BytesAndSend(address,bytes,bytes32)": FunctionFragment;
    "check32BytesAndSendMulti(address[],bytes[],bytes32[])": FunctionFragment;
    "check32BytesAndSendMultiWETH(uint256,address[],bytes[],bytes32[])": FunctionFragment;
    "check32BytesAndSendWETH(uint256,address,bytes,bytes32)": FunctionFragment;
    "checkBytesAndSend(address,bytes,bytes)": FunctionFragment;
    "checkBytesAndSendMulti(address[],bytes[],bytes[])": FunctionFragment;
    "checkBytesAndSendMultiWETH(uint256,address[],bytes[],bytes[])": FunctionFragment;
    "checkBytesAndSendWETH(uint256,address,bytes,bytes)": FunctionFragment;
    "weth()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "check32BytesAndSend",
    values: [string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "check32BytesAndSendMulti",
    values: [string[], BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "check32BytesAndSendMultiWETH",
    values: [BigNumberish, string[], BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "check32BytesAndSendWETH",
    values: [BigNumberish, string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkBytesAndSend",
    values: [string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkBytesAndSendMulti",
    values: [string[], BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "checkBytesAndSendMultiWETH",
    values: [BigNumberish, string[], BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "checkBytesAndSendWETH",
    values: [BigNumberish, string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "weth", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "check32BytesAndSend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "check32BytesAndSendMulti",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "check32BytesAndSendMultiWETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "check32BytesAndSendWETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkBytesAndSend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkBytesAndSendMulti",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkBytesAndSendMultiWETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkBytesAndSendWETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "weth", data: BytesLike): Result;

  events: {};
}

export class MevBriber extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MevBriberInterface;

  functions: {
    check32BytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "check32BytesAndSend(address,bytes,bytes32)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    check32BytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "check32BytesAndSendMulti(address[],bytes[],bytes32[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    check32BytesAndSendMultiWETH(
      _bribeAmount: BigNumberish,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "check32BytesAndSendMultiWETH(uint256,address[],bytes[],bytes32[])"(
      _bribeAmount: BigNumberish,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    check32BytesAndSendWETH(
      _bribeAmount: BigNumberish,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "check32BytesAndSendWETH(uint256,address,bytes,bytes32)"(
      _bribeAmount: BigNumberish,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    checkBytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "checkBytesAndSend(address,bytes,bytes)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    checkBytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "checkBytesAndSendMulti(address[],bytes[],bytes[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    checkBytesAndSendMultiWETH(
      _bribeAmount: BigNumberish,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "checkBytesAndSendMultiWETH(uint256,address[],bytes[],bytes[])"(
      _bribeAmount: BigNumberish,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    checkBytesAndSendWETH(
      _bribeAmount: BigNumberish,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "checkBytesAndSendWETH(uint256,address,bytes,bytes)"(
      _bribeAmount: BigNumberish,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    weth(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "weth()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  check32BytesAndSend(
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "check32BytesAndSend(address,bytes,bytes32)"(
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  check32BytesAndSendMulti(
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "check32BytesAndSendMulti(address[],bytes[],bytes32[])"(
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  check32BytesAndSendMultiWETH(
    _bribeAmount: BigNumberish,
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "check32BytesAndSendMultiWETH(uint256,address[],bytes[],bytes32[])"(
    _bribeAmount: BigNumberish,
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  check32BytesAndSendWETH(
    _bribeAmount: BigNumberish,
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "check32BytesAndSendWETH(uint256,address,bytes,bytes32)"(
    _bribeAmount: BigNumberish,
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  checkBytesAndSend(
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "checkBytesAndSend(address,bytes,bytes)"(
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  checkBytesAndSendMulti(
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "checkBytesAndSendMulti(address[],bytes[],bytes[])"(
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  checkBytesAndSendMultiWETH(
    _bribeAmount: BigNumberish,
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "checkBytesAndSendMultiWETH(uint256,address[],bytes[],bytes[])"(
    _bribeAmount: BigNumberish,
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  checkBytesAndSendWETH(
    _bribeAmount: BigNumberish,
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "checkBytesAndSendWETH(uint256,address,bytes,bytes)"(
    _bribeAmount: BigNumberish,
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  weth(overrides?: CallOverrides): Promise<string>;

  "weth()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    check32BytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "check32BytesAndSend(address,bytes,bytes32)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    check32BytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "check32BytesAndSendMulti(address[],bytes[],bytes32[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    check32BytesAndSendMultiWETH(
      _bribeAmount: BigNumberish,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "check32BytesAndSendMultiWETH(uint256,address[],bytes[],bytes32[])"(
      _bribeAmount: BigNumberish,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    check32BytesAndSendWETH(
      _bribeAmount: BigNumberish,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "check32BytesAndSendWETH(uint256,address,bytes,bytes32)"(
      _bribeAmount: BigNumberish,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    checkBytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "checkBytesAndSend(address,bytes,bytes)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    checkBytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "checkBytesAndSendMulti(address[],bytes[],bytes[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    checkBytesAndSendMultiWETH(
      _bribeAmount: BigNumberish,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "checkBytesAndSendMultiWETH(uint256,address[],bytes[],bytes[])"(
      _bribeAmount: BigNumberish,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    checkBytesAndSendWETH(
      _bribeAmount: BigNumberish,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "checkBytesAndSendWETH(uint256,address,bytes,bytes)"(
      _bribeAmount: BigNumberish,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    weth(overrides?: CallOverrides): Promise<string>;

    "weth()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    check32BytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "check32BytesAndSend(address,bytes,bytes32)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    check32BytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "check32BytesAndSendMulti(address[],bytes[],bytes32[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    check32BytesAndSendMultiWETH(
      _bribeAmount: BigNumberish,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "check32BytesAndSendMultiWETH(uint256,address[],bytes[],bytes32[])"(
      _bribeAmount: BigNumberish,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    check32BytesAndSendWETH(
      _bribeAmount: BigNumberish,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "check32BytesAndSendWETH(uint256,address,bytes,bytes32)"(
      _bribeAmount: BigNumberish,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    checkBytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "checkBytesAndSend(address,bytes,bytes)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    checkBytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "checkBytesAndSendMulti(address[],bytes[],bytes[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    checkBytesAndSendMultiWETH(
      _bribeAmount: BigNumberish,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "checkBytesAndSendMultiWETH(uint256,address[],bytes[],bytes[])"(
      _bribeAmount: BigNumberish,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    checkBytesAndSendWETH(
      _bribeAmount: BigNumberish,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "checkBytesAndSendWETH(uint256,address,bytes,bytes)"(
      _bribeAmount: BigNumberish,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    weth(overrides?: CallOverrides): Promise<BigNumber>;

    "weth()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    check32BytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "check32BytesAndSend(address,bytes,bytes32)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    check32BytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "check32BytesAndSendMulti(address[],bytes[],bytes32[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    check32BytesAndSendMultiWETH(
      _bribeAmount: BigNumberish,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "check32BytesAndSendMultiWETH(uint256,address[],bytes[],bytes32[])"(
      _bribeAmount: BigNumberish,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    check32BytesAndSendWETH(
      _bribeAmount: BigNumberish,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "check32BytesAndSendWETH(uint256,address,bytes,bytes32)"(
      _bribeAmount: BigNumberish,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    checkBytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "checkBytesAndSend(address,bytes,bytes)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    checkBytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "checkBytesAndSendMulti(address[],bytes[],bytes[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    checkBytesAndSendMultiWETH(
      _bribeAmount: BigNumberish,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "checkBytesAndSendMultiWETH(uint256,address[],bytes[],bytes[])"(
      _bribeAmount: BigNumberish,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    checkBytesAndSendWETH(
      _bribeAmount: BigNumberish,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "checkBytesAndSendWETH(uint256,address,bytes,bytes)"(
      _bribeAmount: BigNumberish,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    weth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "weth()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
